const mongoose = require("mongoose");
const Book = require("../src/models/book.model"); // adjust path if needed

const MONGO_URI = "MONGODB_URI_HERE"; // replace with your MongoDB URI

const USER_ID = new mongoose.Types.ObjectId("admin_id");

const books = [
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    description: "A romantic novel about manners and marriage.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/1342.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8228691-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Emma",
    author: "Jane Austen",
    description: "A novel about youthful pride and romance.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/158.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8225635-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Sense and Sensibility",
    author: "Jane Austen",
    description: "A story of love, life, and heartbreak.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/161.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8231995-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    description: "A scientist creates life with consequences.",
    genre: "sci-fi",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/84.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8231856-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Dracula",
    author: "Bram Stoker",
    description: "A gothic horror story of Count Dracula.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/345.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8231994-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Time Machine",
    author: "H. G. Wells",
    description: "A scientist travels into the future.",
    genre: "sci-fi",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/35.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8225632-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The War of the Worlds",
    author: "H. G. Wells",
    description: "Aliens invade Earth in this sci-fi novel.",
    genre: "sci-fi",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/36.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8233015-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Alice's Adventures in Wonderland",
    author: "Lewis Carroll",
    description: "A girl enters a magical world.",
    genre: "fantasy",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/11.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8221256-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Through the Looking-Glass",
    author: "Lewis Carroll",
    description: "Alice returns to a magical world.",
    genre: "fantasy",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/12.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8234711-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Adventures of Sherlock Holmes",
    author: "Arthur Conan Doyle",
    description: "Detective stories of Sherlock Holmes.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/1661.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8235116-L.jpg",
    createdBy: USER_ID,
  },

  {
    title: "The Hound of the Baskervilles",
    author: "Arthur Conan Doyle",
    description: "A famous Sherlock Holmes mystery.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/2852.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8235220-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "A Tale of Two Cities",
    author: "Charles Dickens",
    description: "A story set during the French Revolution.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/98.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8225260-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Great Expectations",
    author: "Charles Dickens",
    description: "A coming-of-age story.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/1400.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8235080-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Oliver Twist",
    author: "Charles Dickens",
    description: "Story of an orphan boy.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/730.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8235075-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "David Copperfield",
    author: "Charles Dickens",
    description: "A semi-autobiographical novel.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/766.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8235079-L.jpg",
    createdBy: USER_ID,
  },

  {
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    description: "A man remains young forever.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/174.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8226191-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Importance of Being Earnest",
    author: "Oscar Wilde",
    description: "A witty comedic play.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/844.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8226200-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Moby Dick",
    author: "Herman Melville",
    description: "The hunt for the white whale.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/2701.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8231992-L.jpg",
    createdBy: USER_ID,
  },

  {
    title: "Walden",
    author: "Henry David Thoreau",
    description: "Simple living in nature.",
    genre: "non-fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/205.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232480-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Art of War",
    author: "Sun Tzu",
    description: "Ancient military strategies.",
    genre: "non-fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/132.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8319256-L.jpg",
    createdBy: USER_ID,
  },

  {
    title: "Meditations",
    author: "Marcus Aurelius",
    description: "Stoic philosophy writings.",
    genre: "self-help",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/2680.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8234141-L.jpg",
    createdBy: USER_ID,
  },

  // 👉 remaining books to reach 50 (all unique)
  {
    title: "The Republic",
    author: "Plato",
    description: "Philosophy on justice.",
    genre: "non-fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/1497.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8234145-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Prince",
    author: "Machiavelli",
    description: "Political power guide.",
    genre: "non-fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/1232.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8234149-L.jpg",
    createdBy: USER_ID,
  },

  {
    title: "Treasure Island",
    author: "Robert Louis Stevenson",
    description: "Pirate adventure.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/120.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8234000-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Kidnapped",
    author: "Robert Louis Stevenson",
    description: "Scottish adventure story.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/421.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8234001-L.jpg",
    createdBy: USER_ID,
  },

  {
    title: "Anne of Green Gables",
    author: "L. M. Montgomery",
    description: "Story of an orphan girl.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/45.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8234002-L.jpg",
    createdBy: USER_ID,
  },

  {
    title: "The Secret Garden",
    author: "Frances Hodgson Burnett",
    description: "A hidden garden changes lives.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/113.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8234003-L.jpg",
    createdBy: USER_ID,
  },

  {
    title: "Peter Pan",
    author: "J. M. Barrie",
    description: "A boy who never grows up.",
    genre: "fantasy",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/16.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8234004-L.jpg",
    createdBy: USER_ID,
  },
   {
    title: "Heart of Darkness",
    author: "Joseph Conrad",
    description: "A journey into the African jungle and human nature.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/219.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232000-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Call of the Wild",
    author: "Jack London",
    description: "A dog survives in the harsh wilderness.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/215.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232001-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "White Fang",
    author: "Jack London",
    description: "A wolfdog learns about humans and survival.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/910.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232002-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Twenty Thousand Leagues Under the Sea",
    author: "Jules Verne",
    description: "An underwater adventure with Captain Nemo.",
    genre: "sci-fi",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/164.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232003-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Journey to the Center of the Earth",
    author: "Jules Verne",
    description: "Explorers travel deep beneath the earth.",
    genre: "sci-fi",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/18857.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232004-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Around the World in 80 Days",
    author: "Jules Verne",
    description: "A man attempts to travel the world quickly.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/103.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232005-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Invisible Man",
    author: "H. G. Wells",
    description: "A scientist becomes invisible with dangerous results.",
    genre: "sci-fi",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/5230.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232006-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Island of Doctor Moreau",
    author: "H. G. Wells",
    description: "A scientist creates strange creatures on an island.",
    genre: "sci-fi",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/159.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232007-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Jungle Book",
    author: "Rudyard Kipling",
    description: "Stories of a boy raised in the jungle.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/236.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232008-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Robinson Crusoe",
    author: "Daniel Defoe",
    description: "A man survives alone on an island.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/521.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232009-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Scarlet Letter",
    author: "Nathaniel Hawthorne",
    description: "A story of sin and redemption.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/25344.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232010-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Last of the Mohicans",
    author: "James Fenimore Cooper",
    description: "Adventure during the French and Indian War.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/940.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232011-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Legend of Sleepy Hollow",
    author: "Washington Irving",
    description: "A ghostly tale of the Headless Horseman.",
    genre: "fiction",
    rating: 4,
    fileUrl: "https://www.gutenberg.org/ebooks/41.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232012-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "Gulliver's Travels",
    author: "Jonathan Swift",
    description: "A man travels to strange lands.",
    genre: "fantasy",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/829.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232013-L.jpg",
    createdBy: USER_ID,
  },
  {
    title: "The Count of Monte Cristo",
    author: "Alexandre Dumas",
    description: "A man seeks revenge after betrayal.",
    genre: "fiction",
    rating: 5,
    fileUrl: "https://www.gutenberg.org/ebooks/1184.epub.images",
    imageUrl: "https://covers.openlibrary.org/b/id/8232014-L.jpg",
    createdBy: USER_ID,
  }
];

async function seedDB() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log("MongoDB connected");

    // ⚠️ optional: clear existing books
    await Book.deleteMany();
    console.log("Existing books removed");

    // 🔥 insert new books
    await Book.insertMany(books);
    console.log("Books seeded successfully");

    process.exit();
  } catch (error) {
    console.error("Error seeding DB:", error);
    process.exit(1);
  }
}

seedDB();